# Pipeline condicional
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build and Test
        script:
          - if git diff --name-only $BITBUCKET_COMMIT_PREV..$BITBUCKET_COMMIT | grep -q 'frontend'; then
              echo "Building and testing frontend code."
              # Insert commands to build and test frontend code here.
            elif git diff --name-only $BITBUCKET_COMMIT_PREV..$BITBUCKET_COMMIT | grep -q 'backend'; then
              echo "Building and testing backend code."
              # Insert commands to build and test backend code here.
            else
              echo "No frontend or backend files modified, skipping build and test."
            fi

